### PR TITLE
Register bedrock item at OreDictionary.

### PR DESCRIPTION
**Pull request by V10lator**
You don't have to worry about mod conflicts, I tested the OreDict and multiple mods registring the same item is fine.

### CODE REVIEW

**Comment by jredfox** [comment]
this isn't what I was hoping for at all. I thought you were going to register bedrock redstone lapis, etc....

Also what would the point of the oredictionary be if I am not going to be using the recipes?

**Comment by V10lator** [comment]
Redstone & co are already registered by vanilla. Registering bedrock alows to use it in recipes for _other_ mods (example: I wrote custom recipes for Sparks hammers. Redstone & co hammers worked right away but bedrock hammer needs this patch).

//EDIT: Here's what I wrote to config/sparkshammers/customTools.json to give it "vanilla-life hammers":

```
    {
        "MaterialName": "obsidian",
        "LocalisedName": "Obsidian",
        "HarvestLevel": 4,
        "Durability": 6500,
        "Efficiency": 8.0,
        "AttackDamage": 5.0,
        "Enchantability": 13,
        "TextureColour": 0x100026,
        "DependantOreDic": "obsidian"
    },
    {
        "MaterialName": "bedrock",
        "LocalisedName": "Bedrock",
        "HarvestLevel": 5,
        "Durability": 25000,
        "Efficiency": 14.0,
        "AttackDamage": 7.0,
        "Enchantability": 11,
        "TextureColour": 0x555555,
        "DependantOreDic": "bedrock"
    },
    {
        "MaterialName": "redstone",
        "LocalisedName": "Redstone",
        "HarvestLevel": 2,
        "Durability": 500,
        "Efficiency": 18.0,
        "AttackDamage": 6.0,
        "Enchantability": 12,
        "TextureColour": 0x800000,
        "DependantOreDic": "blockRedstone"
    },
    {
        "MaterialName": "lapis",
        "LocalisedName": "Lapis",
        "HarvestLevel": 2,
        "Durability": 185,
        "Efficiency": 7.0,
        "AttackDamage": 12.0,
        "Enchantability": 26,
        "TextureColour": 0x008fff,
        "DependantOreDic": "blockLapis"
    },
    {
        "MaterialName": "quartz",
        "LocalisedName": "Quartz",
        "HarvestLevel": 2,
        "Durability": 800,
        "Efficiency": 8.0,
        "AttackDamage": 3.0,
        "Enchantability": 10,
        "TextureColour": 0xffffff,
        "DependantOreDic": "blockQuartz"
    }
```

I hope you understand now why registering a none-vanilla item (bedrock) is needed while vanilla items work out of the box. :)

**Comment by jredfox** [comment]
right but, that's got to be a mod doing it right? Also they are not using the proper format of gemDiamond,ingotIron,blockCoal etc... I guess I could go through and add them later. I am busy setting up with omniarchive people. got sounds most mc clients now we just need the servers and I am set

**Comment by V10lator** [comment]
You still missunderstand. This is what I wrote, they aren't using it by now (might make a pull request later). Anyway, vanilla knows bedrock as block only, not as item. You are adding it as item, so you are responsible for making the OreDictionary entry, too, to allow other mods to use the item in recipes. It's really only that one single line of code that's needed.

**Comment by jredfox** [comment]
no I don't add bedrock as an item that I know of show me where I do that? I said I would look to see why bedrock is missing but, the other entries sounds like a mod not fallowing protocals when adding entries

**Comment by V10lator** [comment]
One of the key things of your mod is to transform bedrock to an item so you can use it in your recipes. Currently you just don't allow other mods to use the new item as you're not registering it to the OreDictionary.

Here you make bedrock breakable, which vanilla doesn't do:
https://github.com/jredfox/vanillalife/blob/master/src/main/java/com/evilnotch/vanillalife/MainJava.java#L188

And here you add it as an item to the world - an item which doesn't exist without your mod (as bedrock is unbreakable) :
https://github.com/jredfox/vanillalife/blob/master/src/main/java/com/evilnotch/vanillalife/MainJava.java#L200

**Comment by jredfox** [comment]
if you look in vanilla creative mode bedrock is a vanilla item. It's already available via the /give command. So I don't add it into the game. If I did you would see ForgeRegistries.register(new ItemBlock(Blocks.BEDROCK));

Either way your pull sucks and lack of understanding of code and minecraft mechanics. That's like saying I should add aoa:candyblock22 because I make it drop with silktouch to an dictionary.

Your hostility is unacceptable to. I said I would look into it but, either way A: your config names shown in comments are wrong and still no explanation as to why only bedrock. I already stated based on two seconds of forge documentation on what the format should be the way that file is is wrong.

I was simply keeping this open only as a reminder to add all vanilla entries as an enhancement myself but, your hostility made me close this

**Pull request closed without merging**
